project_id = "ornnzinjrcyigazecctf"

[functions.ai-candidate-explanation]
verify_jwt = false

[functions.ai-profile-summary]
verify_jwt = false

[functions.fetch-representatives]
verify_jwt = false

[functions.fetch-member]
verify_jwt = false

[functions.fetch-member-votes]
verify_jwt = false

[functions.user-profile-analysis]
verify_jwt = false

[functions.geocode-address]
verify_jwt = false

[functions.google-places-autocomplete]
verify_jwt = false

[functions.google-places-details]
verify_jwt = false

[functions.validate-address]
verify_jwt = false