project_id = "ornnzinjrcyigazecctf"

[functions.ai-candidate-explanation]
verify_jwt = false

[functions.ai-profile-summary]
verify_jwt = false

[functions.fetch-representatives]
verify_jwt = false

[functions.fetch-member]
verify_jwt = false

[functions.fetch-member-votes]
verify_jwt = false

[functions.user-profile-analysis]
verify_jwt = false